steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/${PROJECT_ID}/${TRIGGER_NAME}:${SHORT_SHA}'
      - '--build-arg'
      - 'REACT_APP_INFURA_KEY=${_REACT_APP_INFURA_KEY}'
      - '--build-arg'
      - 'REACT_APP_FORTMATIC_KEY=${_REACT_APP_FORTMATIC_KEY}'
      - '--build-arg'
      - 'REACT_APP_GOOGLE_ANALYTICS_ID=${_REACT_APP_GOOGLE_ANALYTICS_ID}'
      # folder name for context
      - '$TRIGGER_NAME/'
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/${PROJECT_ID}/${TRIGGER_NAME}:${SHORT_SHA}'
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - '${TRIGGER_NAME}'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/${TRIGGER_NAME}:${SHORT_SHA}'
      - '--region'
      - us-central1
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    id: publish
timeout: 1800s
