steps:
  - name: bash
    args:
      - '-c'
      - 'cp $TRIGGER_NAME/npmrc-template $TRIGGER_NAME/.npmrc'
    id: cptemplate
  - name: gcr.io/cloud-builders/npm
    args:
      - google-artifactregistry-auth
      - '$TRIGGER_NAME/.npmrc'
    id: npmrc
    entrypoint: npx
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/$TRIGGER_NAME:$SHORT_SHA'
      - '--build-arg'
      - 'REACT_APP_HASURA_API_ENDPOINT_WS=${_REACT_APP_HASURA_API_ENDPOINT_WS}'
      - '--build-arg'
      - 'REACT_APP_HASURA_ADMIN_SECRET=${_REACT_APP_HASURA_ADMIN_SECRET}'
      - '--build-arg'
      - 'REACT_APP_ENABLE_RINKEBY=${_REACT_APP_ENABLE_RINKEBY}'
      - '--build-arg'
      - 'REACT_APP_ENABLE_VELOX_WIDGET_MODE=${_REACT_APP_ENABLE_VELOX_WIDGET_MODE}'
      - '--build-arg'
      - 'REACT_APP_ENABLE_VELOX_WIDGET_TEST=${_REACT_APP_ENABLE_VELOX_WIDGET_TEST}'
      - '--build-arg'
      - 'REACT_APP_AVALANCHE_MAINNET_PROXY=${_REACT_APP_AVALANCHE_MAINNET_PROXY}'
      - '--build-arg'
      - 'REACT_APP_STRATEGY_API_URI=${_REACT_APP_STRATEGY_API_URI}'
      - '--build-arg'
      - 'REACT_APP_STRATEGY_API_KEY=${_REACT_APP_STRATEGY_API_KEY}'
      - '--build-arg'
      - 'REACT_APP_TOKEN_SYNC_URI=${_REACT_APP_TOKEN_SYNC_URI}'
      - '--build-arg'
      - 'REACT_APP_GA_CODE=${_REACT_APP_GA_CODE}'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_WEB_API_KEY=${_REACT_APP_FIREBASE_WEB_API_KEY}'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_CHART_DATA_STORAGE=${_REACT_APP_FIREBASE_CHART_DATA_STORAGE}'
      - '--build-arg'
      - 'REACT_APP_ROME_ENV=${_REACT_APP_ROME_ENV}'
      - '--build-arg'
      - 'REACT_APP_KYBER_MAINNET_ENV=${_REACT_APP_KYBER_MAINNET_ENV}'
      - '--build-arg'
      - 'REACT_APP_KYBER_INFURA_KEY=${_REACT_APP_KYBER_INFURA_KEY}'
      - '--build-arg'
      - 'REACT_APP_KYBER_AGGREGATOR_API=${_REACT_APP_KYBER_AGGREGATOR_API}'
      - '--build-arg'
      - 'REACT_APP_KYBER_AGGREGATOR_STATS_API=${_REACT_APP_KYBER_AGGREGATOR_STATS_API}'
      - '--build-arg'
      - 'REACT_APP_KYBER_KRYSTAL_API=${_REACT_APP_KYBER_KRYSTAL_API}'
      - '--build-arg'
      - 'REACT_APP_SHARE_PROXY_URL=${_REACT_APP_SHARE_PROXY_URL}'
      - '--build-arg'
      - 'GENERATE_SOURCEMAP=${_GENERATE_SOURCEMAP}'
      # folder name for context
      - '$TRIGGER_NAME/'
  - name: gcr.io/cloud-builders/docker
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/$TRIGGER_NAME'
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - '${TRIGGER_NAME}'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/${TRIGGER_NAME}:${SHORT_SHA}'
      - '--region'
      - us-central1
      - '--tag'
      - '${_BRANCH_COMMIT_TAG_SANITIZED}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    id: publish
timeout: 1800s
options:
  machineType: 'E2_HIGHCPU_32'
  dynamic_substitutions: true
substitutions:
  #Combined traffic tag and service name cannot exceed 46 characters.
  # 46 chars minus (rt-prod (service name) + - + shortSha) leaves 31 chars, truncating to 25 for safety
  _BRANCH_NAME_SHORT: ${BRANCH_NAME:0:25}
  _BRANCH_COMMIT_TAG: ${_BRANCH_NAME_SHORT}-${SHORT_SHA}
  _BRANCH_COMMIT_TAG_LOWERCASE: ${_BRANCH_COMMIT_TAG,,}
  _BRANCH_COMMIT_TAG_SANITIZED: ${_BRANCH_COMMIT_TAG_LOWERCASE/:/-} #it would be better if we could regex and remove all non alphanumerics
