steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/$TRIGGER_NAME:$SHORT_SHA'
      - '$TRIGGER_NAME/'
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/$TRIGGER_NAME'
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      # - '${_CLOUD_RUN_DEPLOY_NAME}'
      - '$PROJECT_ID'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/${TRIGGER_NAME}:${SHORT_SHA}'
      - '--region'
      - us-central1
      - '--tag'
      - '${_BRANCH_COMMIT_TAG_SANITIZED}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    id: publish
timeout: 1800s
options:
  machineType: 'E2_HIGHCPU_8'
  dynamic_substitutions: true
substitutions:
  #Combined traffic tag and service name cannot exceed 46 characters.
  _BRANCH_NAME_SHORT: ${BRANCH_NAME:0:25}
  _BRANCH_COMMIT_TAG: ${_BRANCH_NAME_SHORT}-${SHORT_SHA}
  _BRANCH_COMMIT_TAG_LOWERCASE: ${_BRANCH_COMMIT_TAG,,}
  _BRANCH_COMMIT_TAG_SANITIZED: ${_BRANCH_COMMIT_TAG_LOWERCASE/:/-} #it would be better if we could regex and remove all non alphanumerics

